version: "3.9"

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: dexter-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
